Better error handling and reporting, Usage output, reporting

diff --git a/files/ssh-ca b/files/ssh-ca
--- a/files/ssh-ca
+++ b/files/ssh-ca
@@ -14,75 +14,104 @@ function log_debug() {
 function log_output() {
     log_debug "CALL ${*}"
     output="$("${@}" 2>&1)"
+    rc=$?
+    log_debug "RETURN ${rc}"
     log_debug "OUTPUT ${output}"
+    return ${rc}
 }
 
 function log_certificate() {
-    ssh-keygen -L -f "${cert}" >> /var/log/ssh-ca/signatures.log
+    cat "${cert}" >> /var/log/ssh-ca/certificates.log
 }
 
-function sign_user_key() {
+function sign_key() {
+    # Files and IO related variables
     mkdir -p /tmp/ssh-ca
-    principals="${SSH_ORIGINAL_COMMAND#* }"
     pubkey="/tmp/ssh-ca/${run_id}.pub"
     cert="/tmp/ssh-ca/${run_id}-cert.pub"
+
+    # Expect a public key on stdin
     dd bs=1K count=10 of="${pubkey}" 2>/dev/null
+    log_output ssh-keygen -l -f "${pubkey}"
+    rc=$?
+    if [ ${rc} -gt 0 ]; then
+        echo ERROR: input is not a well-formed SSH public key
+        rm "${pubkey}"
+        exit ${rc}
+    fi
+
+    # Certificate signature parameters
     ca_key="/usr/local/lib/ssh-ca/${SSH_CA_KEY}"
     serial="$(date +%s)"
-    validity="${SSH_CA_CERTIFICATE_VALIDITY}"
-    if [ -n "${SSH_CA_CERTIFICATE_OPTIONS}" ]; then
-        options=" -O ${SSH_CA_CERTIFICATE_OPTIONS}"
+    principals="${arguments[1]}"
+    if [ "${arguments[0]}" = "user" ]; then
+        validity="${SSH_CA_CERTIFICATE_VALIDITY}"
+        options="${SSH_CA_CERTIFICATE_OPTIONS}"
+        host_cert=""
     else
+        validity="+365d"
         options=""
+        host_cert="-h"
     fi
+
+    # Validation
+    if [ -z "${principals}" ]; then
+        log_debug "ERROR: Empty PRINCIPALS parameter"
+        echo "ERROR: The PRINCIPALS parameter cannot be empty"
+        exit 1
+    fi
+
+    # Actual signature happens here
     log_output ssh-keygen \
         -P "" \
         -s "/usr/local/lib/ssh-ca/${SSH_CA_KEY}" \
+        ${host_cert} \
         -I "${user_id}" \
         -V "${validity}"${options} \
         -n "${principals}" \
         -z "${serial}" \
         "${pubkey}"
-    log_certificate
-    cat "${cert}"
-    rm "${pubkey}"
-    rm "${cert}"
-}
+    rc=$?
 
-function sign_host_key() {
-    mkdir -p /tmp/ssh-ca
-    pubkey="/tmp/ssh-ca/${run_id}.pub"
-    cert="/tmp/ssh-ca/${run_id}-cert.pub"
-    dd bs=1K count=10 of="${pubkey}" 2>/dev/null
-    ca_key="/usr/local/lib/ssh-ca/${SSH_CA_KEY}"
-    validity="+365d"
-    log_output ssh-keygen \
-        -P "" \
-        -s "/usr/local/lib/ssh-ca/${SSH_CA_KEY}" \
-        -h \
-        -I "${SSH_CA_KEY}" \
-        -V "${validity}" \
-        "${pubkey}"
-    cat "${cert}"
-    log_certificate
+    # Cleanup
     rm "${pubkey}"
-    rm "${cert}"
+    if [ ${rc} -eq 0 ]; then
+        log_certificate
+        cat "${cert}"
+        rm "${cert}"
+    else
+        echo "ERROR: no certificate was produced"
+        echo "See the debug log on the CA server for more details"
+        exit ${rc}
+    fi
 }
 
 log_debug "SSH_ORIGINAL_COMMAND ${SSH_ORIGINAL_COMMAND}"
-subcommand=${SSH_ORIGINAL_COMMAND% *}
-case "${subcommand}" in
-    user)
-        sign_user_key
+read -a arguments <<< "${SSH_ORIGINAL_COMMAND}"
+case "${arguments[0]}" in
+    user|host)
+        sign_key "${subcommand}"
         ;;
-    host)
-        sign_host_key
+    report)
+        cat "/var/log/ssh-ca/certificates.log"
         ;;
-    config)
-        echo SSH_ORIGINAL_COMMAND=$SSH_ORIGINAL_COMMAND
-        echo USER=$user_id
-        echo SSH_CA_KEY=$SSH_CA_KEY
-        echo SSH_CA_CERTIFICATE_VALIDITY=$SSH_CA_CERTIFICATE_VALIDITY
-        echo SSH_CA_CERTIFICATE_OPTIONS=$SSH_CA_CERTIFICATE_OPTIONS
+    *)
+        echo Usage:
+        echo "    host PRINCIPALS"
+        echo "                     Sign a host certificate"
+        echo "    user PRINCIPALS"
+        echo "                     Sign a user certificate"
+        echo "    PRINCIPALS is a mandatory comma-separated list of principals"
+        echo "               to include in the signed certificate"
+        echo "    report"
+        echo "            Print the list of all certificates ever signed"
+        echo "            Example report details on the last 10 certificates:"
+        echo "            $ ssh ssh-ca report | ssh-keygen -L -f <(tail)"
+        echo ""
+        echo "COMMAND=$SSH_ORIGINAL_COMMAND"
+        echo "USER=$user_id"
+        echo "SSH_CA_KEY=$SSH_CA_KEY"
+        echo "SSH_CA_CERTIFICATE_VALIDITY=$SSH_CA_CERTIFICATE_VALIDITY"
+        echo "SSH_CA_CERTIFICATE_OPTIONS=$SSH_CA_CERTIFICATE_OPTIONS"
         ;;
 esac
